# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Guo Yanli
email: guoyanli.psnl@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal blog site, served by github pages. I will share some IT
  technology artices and some interesting blogs, pages here.
baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://yanliguo.github.io" # the base hostname & protocol for your site
twitter_username: yanliguo
github_username:  yanliguo

# Build settings
markdown: kramdown
