# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Yanli Blog 
email: guoyanli.psnl@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is yanli blog, sharing some articles about IT technology, network architectures, machine learning topics.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yanliguo.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username: yanliguo 

# Build settings
markdown: kramdown
